manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: 35c46048d330ce1bea9248d4dd6a9879d0fe5be7
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          #- lvgl      # Uncomment to include LittlevGL for the git bisect demo
          - cmsis      # required by the ARM port
          - cmsis_6
          - mbedtls
          - openthread
          - tf-psa-crypto
          - hal_nordic
          - hal_rpi_pico
          - segger
