# SEGGER SystemView via RTT (for hardware boards like nrf52840dk)

CONFIG_TRACING=y
CONFIG_SEGGER_SYSTEMVIEW=y

# Trace events
CONFIG_TRACING_THREAD=y
CONFIG_TRACING_ISR=y
CONFIG_TRACING_SEMAPHORE=y
CONFIG_TRACING_MUTEX=y
CONFIG_TRACING_WORK=y
CONFIG_TRACING_SYSCALL=y

# Thread names in trace output
CONFIG_THREAD_NAME=y
CONFIG_DEBUG_THREAD_INFO=y
