# SPDX-FileCopyrightText: Copyright (c) 2026 Navimatix GmbH
# SPDX-FileCopyrightText: Copyright (c) 2026 TiaC Systems
# SPDX-License-Identifier: Apache-2.0

# display API on top of an LED strip matrix
CONFIG_DISPLAY=y
CONFIG_LED_STRIP=y

# console output and logging
CONFIG_BOOT_BANNER=y
CONFIG_LOG=y
CONFIG_PRINTK=y
