name: Build Samples

on:
  push:
    branches:
      - main
      - stuttgart-09.27
  pull_request:
    branches:
      - main
      - stuttgart-09.27
  schedule:
    - cron: '0 8 * * *'  # Run daily at 8 AM UTC
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jonas-rem/zephyr-workshop/devcontainer:latest
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Initialize West
        run: |
          git config --global --add safe.directory '*'
          for name in zephyr modules; do
            if [ ! -e "../$name" ]; then
              ln -s "/opt/zephyrproject/$name" "../$name"
            fi
          done
          west init -l .
          west update --narrow -o=--depth=1
          west zephyr-export

      - name: Install Dependencies
        run: |
          pip install --break-system-packages \
            -r ../zephyr/scripts/requirements.txt

      - name: Build and Test
        env:
          ZEPHYR_BASE: /opt/zephyrproject/zephyr
        run: |
          west twister -T app -T samples --integration --exclude-tag workshop
